[package]
name = "pangotrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.17.0", features = ["png"] }
pango = "0.17.4"
pangocairo = "0.17.0"
